restrictcontentpro/restrict-content-pro

templates/register.php

Added rcp_before_subscription_form_fields hook to add fields above the price options but below login/registration.

Added rcp_before_subscription_form_fields hook above the price.

---

composer.json

Because no project is complete without it! And besides need it at CGC. ;)

Add Composer File

---

includes/gateways/class-rcp-payment-gateway-stripe.php

Fixing plans not being created when they do not exist, upon purchase

---

includes/admin/admin-notices.php

Ref: https://twitter.com/ShaneGowland/status/594126301943857153/photo/1

Correct grammar of the database upgrade notification

---

includes/admin/subscriptions/subscription-levels.php

Fix description typos

---

includes/admin/subscriptions/edit-subscription.php
includes/admin/subscriptions/subscription-levels.php

change days(s) and years(s)

---

includes/admin/metabox.php
includes/admin/settings/settings.php

add full stops

---

templates/card-form.php
templates/card-update-form.php

Add maxlength to card number and CVC

---

includes/admin/settings/settings.php
includes/email-functions.php

Allows the usage of %useremail% template tag inside emails

Add %useremail% tag to emails

---

templates/register-single.php

Instead of showing / 0 will now show Unlimited if the membership is not set

Show unlimited duration

---

templates/card-form.php
templates/card-update-form.php

fixed fieldset class name. ran a search and didn't see the misspelling used anywhere else except in these two files

fix fieldset name

---

includes/upgrades.php

Check 'status' column in restrict_content_pro table in includes/upgrades.php on line 63 duplicated on line 77. Removed duplicate code from line 77.

Removed Duplicate Code

---

includes/admin/metabox.php

Change link to correct doc

---

includes/content-filters.php

add isset + minor formatting

---

restrict-content-pro.php

Change Setup to Set Up

---

templates/login.php
templates/lostpassword.php
templates/lostpassword_checkemail.php

change logout to log out

---

includes/admin/categories.php

fix thie->this spelling bug on category view. fix #261

---

includes/admin/admin-ajax-actions.php
includes/js/admin-scripts.js

fix user search no result overlay issue

---

includes/class-rcp-payments.php
includes/process-data.php

Clear the total earnings transient when updating a payment 

---

includes/admin/payments/edit-payment.php
includes/admin/payments/new-payment.php
includes/process-data.php

Default to 0.00 and current time, and force numeric amounts 

---

includes/admin/payments/payments-page.php

Remove rcp_message from Edit/Delete links 

---

includes/class-rcp-levels.php

I am working on creating some custom prorating functionality for a client's site and there is currently no way to adjust a subscription price based on current subscription. These filters are meant to allow for customization of subscription level data on the fly.

Add filters to level functions to allow for on the fly customizations

---

bin/install-wp-tests.sh
includes/class-rcp-member.php
includes/deprecated/functions.php
includes/gateways/class-rcp-payment-gateway-manual.php
includes/member-functions.php
includes/registration-functions.php
tests/test-members.php

This PR helps address issues with expiration dates getting out of sync with PayPal. See #239

Introduce calculate_expiration() method

---

includes/admin/metabox.php

I am trying to add BuddyPress specific content restrictions and would like to place them after the default fields while still maintaining control over the functionality.

Add actions to metabox.php

---

includes/gateways/class-rcp-payment-gateway-stripe.php
includes/registration-functions.php

Introduce rcp_set_pending_subscription_on_upgrade() to resolve #294

---

includes/admin/admin-notices.php

Check values for new level creating Part 1 for Fixing #318

add empty fields return text

---

includes/admin/metabox.php

Don't show restriction settings metabox on attachments. #332.

---

includes/process-data.php

Check values for new level creating Part 2 for Fixing #318

validate empty level fields when creating

---

includes/gateways/stripe/functions.php

This function should utilize the args passed in from the action instead of $_POST fields.

update rcp_stripe_update_discount() to use args passed from action

---

includes/gateways/class-rcp-payment-gateway-2checkout.php

#347 
Also did a little bit of clean up of some of the other hooks.

Handle Recurring subscriptions with 2Checkout

---

includes/admin/admin-pages.php
includes/admin/settings/settings.php
includes/admin/tools/system-info.php
includes/admin/tools/tools-page.php
includes/content-filters.php
includes/css/admin-styles.css
includes/member-functions.php
includes/scripts.php
restrict-content-pro.php

Add system info report #330.

---

includes/shortcodes.php

Add shortcodes for user's subscriptions name, id, and expiration

---

includes/admin/payments/payments-page.php
includes/member-functions.php

Fix payments table and add member edit to payments list

---

includes/admin/reports/reports-page.php
includes/class-rcp-payments.php

Add refunds tab to RCP reports.

Add refunds report

---

includes/admin/reports/reports-page.php
includes/class-rcp-payments.php

Refunds - 326

---

includes/integrations/class-rcp-wp-approve-user.php
includes/misc-functions.php

Only show pending message to member when content is restricted. #362.

---

includes/admin/members/members-page.php
includes/process-data.php

Removes the delete option, to prevent accidental user account deletions. #369.

Remove delete option from bulk actions menu on Members screen. #369.

---

includes/admin/categories.php
includes/content-filters.php
includes/integrations/class-rcp-woocommerce.php
includes/subscription-functions.php

Add support for custom taxonomies - Issue 137

---

includes/process-data.php

Email users when their subscription is added manually. #386.

---

includes/admin/admin-pages.php
includes/admin/tools/tools-page.php
includes/scripts.php

Fix CSS on tools page. Also rename the function to match the page name. #330.

---

includes/class-rcp-member.php
includes/gateways/class-rcp-payment-gateway-2checkout.php
includes/gateways/class-rcp-payment-gateway-paypal-express.php
includes/gateways/class-rcp-payment-gateway-paypal-pro.php
includes/gateways/class-rcp-payment-gateway-paypal.php
includes/gateways/class-rcp-payment-gateway-stripe.php

Matching gateway timezone and PayPal Issues

---

includes/class-rcp-registration.php
includes/gateways/class-rcp-payment-gateway-stripe.php

Set member to recurring when processing Stripe subscriptions. #395.

---

RCP_Plugin_Updater.php
restrict-content-pro.php

Updater RCP_Plugin_Updater class and set new URL and download ID. #401

---

includes/class-rcp-member.php
includes/css/forms.css
includes/gateways/class-rcp-payment-gateway-stripe-checkout.php
includes/gateways/stripe/functions.php
templates/card-update-form.php

Show card details on update card form - Issue/230

---

includes/css/forms.css
includes/gateways/stripe/functions.php
templates/card-update-form.php

Show card details on update card form. #230.

---

ReadMe.md

Update readme links

---

includes/admin/categories.php

Issue #423

---

includes/integrations/class-rcp-woocommerce.php

Fix template override when catalog visibility is hidden. #425.

---

templates/register-total-details.php

Remove description column from price details template. #419

---

templates/register-total-details.php

Remove colspan definition for the Fee Description

---

includes/class-rcp-registration.php
includes/misc-functions.php
includes/registration-functions.php

Run totals through `number_format()` and `rcp_currency_decimal_filter()`. #436.

Introduce rcp_currency_decimal_filter() to handle currency decimal formatting. #436.

---

includes/login-functions.php
includes/registration-functions.php
templates/register-total-details.php

Add missing textdomain to some strings. #448

---

includes/misc-functions.php

Add currency symbol to Brazilian real (R$)

Add symbol for Brazilian Real

---

includes/integrations/class-rcp-woocommerce.php

Properly check levels in WooCommerce integration. #457.

---

includes/misc-functions.php

Add currency signs to rcp_currency_filter

---

includes/admin/members/members-page.php
includes/js/admin-scripts.js
includes/process-data.php
includes/scripts.php

Remove revoke access and reenable access links. #489

---

includes/admin/help/help-menus.php

Add new site support link

---

includes/gateways/class-rcp-payment-gateway-stripe.php

Create a temporary invoice to for customer currency to be set to store currency.

---

includes/css/admin-styles.css
includes/gateways/class-rcp-payment-gateway-paypal-express.php
includes/gateways/class-rcp-payment-gateway-paypal-pro.php
includes/member-functions.php

Update WP HTTP calls to use helper functions - Issue/538

---

includes/content-filters.php
templates/comments-no-access.php

Introduce support for hiding comments automatically if user cannot view post/page - issue / 489

---

includes/admin/metabox-view.php
includes/admin/metabox.php
includes/class-rcp-member.php
includes/content-filters.php

Fix bug in post restriction UI. #584

---

templates/invoice.php

Add email address to html invoice. #588

---

includes/ajax-actions.php
includes/registration-functions.php
includes/subscription-functions.php

Show non-subscribed-to free levels on registration form - issue/565

---

includes/admin/tools/system-info.php
includes/gateways/class-rcp-payment-gateway-2checkout.php
includes/gateways/class-rcp-payment-gateway-manual.php
includes/gateways/class-rcp-payment-gateway-paypal-express.php
includes/gateways/class-rcp-payment-gateway-paypal-pro.php
includes/gateways/class-rcp-payment-gateway-paypal.php
includes/gateways/class-rcp-payment-gateway-stripe.php
includes/gateways/class-rcp-payment-gateway.php
includes/gateways/gateway-functions.php
includes/gateways/paypal/functions.php
includes/gateways/stripe/functions.php
includes/gateways/twocheckout/functions.php
includes/member-functions.php
includes/misc-functions.php
includes/shortcodes.php
tests/test-functions.php

Introduce rcp_is_sandbox() and use it throughout the plugin. #564

---

includes/admin/discounts/discount-codes.php
includes/admin/discounts/edit-discount.php
includes/admin/payments/edit-payment.php
includes/class-rcp-discounts.php
includes/class-rcp-member.php
includes/cron-functions.php
includes/deprecated/functions.php
includes/discount-functions.php
includes/gateways/class-rcp-payment-gateway-paypal-express.php
includes/member-functions.php
includes/process-data.php
templates/invoice.php
templates/subscription.php

Add current time context to strtotime() usage. #591

---

includes/process-data.php

When manually adding users, set the subscription level before setting the status. #592

---

includes/admin/settings/settings.php

issue/610 - Trim API key settings on save.

---

includes/admin/reports/reports-page.php

Fix incorrect date format passed to get_weekstartend().  

---

includes/class-rcp-levels.php
includes/process-data.php

Remove a subscription level's metadata when it is deleted. #590

---

includes/shortcodes.php

Use rcp_is_expired() to check access is [restrict] shortcode. #637

---

includes/class-rcp-member.php

Change the access check in can_access in RCP_Members. #639.

---

includes/gateways/class-rcp-payment-gateway-stripe.php

Round amounts sent to Stripe to zero decimals. #649

---

includes/registration-functions.php

Use existing class instantiations in rcp_process_registration(). #670

---

includes/admin/admin-notices.php
includes/admin/settings/settings.php

Issue / 672 - Show admin notice when log in redirect is enabled without a log in form on the page

---

includes/admin/subscriptions/subscription-levels.php
includes/gateways/class-rcp-payment-gateway-paypal.php
includes/gateways/class-rcp-payment-gateway-stripe.php
includes/gateways/stripe/functions.php
includes/misc-functions.php
includes/registration-functions.php

Use rcp_get_currency() in rcp_currency_filter() instead of getting the currency from options. #690

---

includes/class-rcp-member.php

Do not allow member to be cancelled more than once. #688

---

includes/gateways/class-rcp-payment-gateway-stripe-checkout.php

Correct Stripe Checkout arguments to prevent JS notices and fix functionality

---

includes/gateways/class-rcp-payment-gateway-stripe-checkout.php

Return true instead of false if 100% discounted. #695

---

includes/gateways/class-rcp-payment-gateway-stripe-checkout.php
includes/shortcodes.php

Set data-alipay attribute as a string value. #701

---

includes/gateways/class-rcp-payment-gateway-manual.php

Use current time when calculating expiration date with manual gateway. #721

---

includes/registration-functions.php
templates/register-single.php
templates/register.php

Allow discount code to be pre-filled - issue/95

---

includes/admin/class-rcp-upgrades.php
includes/class-rcp-discounts.php
includes/class-rcp-registration.php
includes/discount-functions.php
restrict-content-pro.php

Set discount codes to case insensitive - issue/529

---

includes/admin/settings/settings.php
includes/member-functions.php

Introduce rcp_maybe_disable_toolbar() and option to disable toolbar #693

---

includes/admin/admin-notices.php

Add dismiss option to license key notices. #553

---

includes/deprecated/functions.php

Update rcp_insert_payment() to use RCP_Payments class. #754

---

includes/misc-functions.php

Fix not preventing account sharing if first user never connects back.

---

includes/member-functions.php

See #769 for details.
Here is an example to add a mandatory 'Description' field to the 'Edit your profile' page: 
https://gist.github.com/geoffreybr/d2dcd2d8db96c432f6f1866099b81d09

Add filters and actions in rcp_process_profile_editor_updates

---

includes/gateways/class-rcp-payment-gateway-stripe.php

Set status after expiration date. #775

---

includes/class-rcp-integrations.php
includes/integrations/class-rcp-easy-digital-downloads.php

#351 
Leaving unmerged until we firm everything up.

Add Easy Digital Downloads integration. #351

---

includes/admin/subscriptions/edit-subscription.php
includes/admin/subscriptions/subscription-levels.php
includes/class-rcp-levels.php

Validate price fields on subscription add/edit screen. #744

---

includes/gateways/stripe/functions.php

Do not retrieve / set discount / card details if Stripe API key is not set - issue/788

---

includes/admin/terms.php
restrict-content-pro.php

WIP.
Also renames functions / file to be generic instead of for categories. #497

Add restriction options to add taxonomy term form - issue/497

---

languages/rcp-es_ES.po

The previous translation was buggy and incomplete. Now it's 💯

Spanish translation fixed and completed

---

restrict-content-pro.php

- Adjusts language loader to provide support for `get_user_locale()`
#783

issue/783: Add support for user locales

---

includes/admin/upgrades.php
includes/install.php
restrict-content-pro.php

Adjust table creation and upgrade routines when network activated. #669

---

includes/css/forms.css
includes/gateways/class-rcp-payment-gateway-stripe-checkout.php
templates/subscription.php

Add attribute for responsive

---

languages/rcp-es_ES.po

Links that doesn't work due to wrong quotes imported from poedit fixed

Fixed links broken

---

includes/admin/members/edit-member.php
includes/process-data.php

Show username and email on edit member screen. #802

---

includes/admin/settings/settings.php
includes/class-rcp-emails.php
includes/email-functions.php
includes/gateways/class-rcp-payment-gateway-2checkout.php
includes/gateways/class-rcp-payment-gateway-paypal-express.php
includes/gateways/class-rcp-payment-gateway-paypal.php
includes/gateways/class-rcp-payment-gateway-stripe.php

Add option to email member when renewal payment fails. #360

---

RCP_Plugin_Updater.php
includes/admin/settings/settings.php
restrict-content-pro.php

Add setting to opt into beta releases. #840

---

includes/admin/metabox-view.php
includes/admin/settings/settings.php
includes/scripts.php

Updated documentation URLs to docs.restrictcontentpro.com #850

---

includes/gateways/class-rcp-payment-gateway.php
includes/gateways/stripe/functions.php

Send new user notification to subscribers when using [register_form_stripe] shortcode. #513

---

includes/admin/class-rcp-upgrades.php

Always set DB versions if version constant is different during upgrades

---

includes/admin/metabox-view.php
includes/admin/metabox.php

Added filter for supported post types. #861

---

includes/class-rcp-member.php
includes/content-filters.php

Check member status when doing taxonomy term restriction checks. #868

---

includes/admin/settings/settings.php
includes/email-functions.php

Issue/884 - Dynamically display list of template tags in settings

---

templates/register-single.php
templates/register.php

Auto select first gateway. #658

---

RCP_Plugin_Updater.php

Updated plugin updater script. #901

---

includes/js/register.js
includes/scripts.php
includes/subscription-functions.php

Pass trial levels to rcp_script_options. #907

---

includes/admin/discounts/discount-codes.php

Change capability check to rcp_manage_discounts. #909

---

includes/class-rcp-emails.php

Run HTML message body through make_clickable(). #915

---

templates/subscription.php

Fixes issue #923
See more info at #924

Add "Payment Status" column to [subscription_details] shortcode

---

includes/gateways/class-rcp-payment-gateway-stripe-checkout.php
includes/js/register.js

Fix variable names in Stripe Checkout javascript. #926

---

includes/login-functions.php

Remove brackets from lost password email link. #892

---

includes/login-functions.php

Check to see if username exists before getting user by email. #854

---

includes/gateways/class-rcp-payment-gateway-paypal-express.php
includes/gateways/class-rcp-payment-gateway-paypal.php
includes/gateways/class-rcp-payment-gateway-stripe.php
includes/process-data.php

Use cancel() method for all cancellations. #858

---

includes/cron-functions.php

Add user note when expiration notice is sent out. #897

---

templates/subscription.php

"Not made any payments" message not spanning full table #941

---

includes/registration-functions.php

Set display name to username if first and last name fields are empty. #849

---

includes/email-functions.php

Disable the mandrill_nl2br filter while sending RCP emails #943

---

includes/registration-functions.php

Don't send 'activated' emails to new trial accounts #882

---

includes/email-functions.php
includes/registration-functions.php

Send email to new free trial members. #935

---

includes/integrations/class-rcp-woocommerce.php

Prevent quick/bulk editing from wiping out WooCommerce product restrictions. #944

---

includes/class-rcp-emails.php

Parse email tags for plain text template. #955

---

includes/member-functions.php
includes/misc-functions.php

Rework rcp_get_current_url() and change action for processing cancellations #860

---

includes/email-functions.php
includes/gateways/class-rcp-payment-gateway-manual.php

Email admin when manual payment is received. #831

---

includes/misc-functions.php

Add extra checks on restricted post meta query. #978

---

includes/class-rcp-member.php

Add dynamic set status hook. #958

---

includes/admin/help/help-menus.php
includes/member-functions.php

Search members by first or last name. #650

---

includes/gateways/gateway-functions.php

Load stripe.js on all pages #970

---

includes/admin/metabox-view.php
includes/admin/metabox.php
includes/admin/settings/settings.php
includes/content-filters.php

Add global setting for content excerpts. #763

---

includes/admin/payments/payments-page.php
includes/deprecated/functions.php
includes/gateways/class-rcp-payment-gateway-paypal.php
includes/subscription-functions.php
templates/subscription.php

Remove/update use of deprecated functions #959

---

includes/shortcodes.php

Add is_expired shortcode

---

includes/gateways/class-rcp-payment-gateway-paypal-express.php

WIP: Fix free trials in PayPal Express. #987

---

includes/gateways/class-rcp-payment-gateway-paypal-express.php

Reverts restrictcontentpro/restrict-content-pro#991

Revert "WIP: Fix free trials in PayPal Express. #987"

---

includes/gateways/class-rcp-payment-gateway-paypal-express.php

Fix free trials in PayPal Express. #987

---

includes/admin/metabox.php

Delete meta if values are empty. #1005

---

includes/admin/settings/settings.php
includes/email-functions.php
includes/js/admin-scripts.js

Improvements to admin email notifications #7

---

includes/admin/settings/settings.php
includes/js/admin-scripts.js
includes/js/register.js
includes/member-forms.php
includes/scripts.php

Add option to specify default auto renew behaviour. #1014

---

includes/admin/help/help-menus-setup.php
includes/admin/help/help-menus.php

Update help tabs. #906

---

includes/gateways/class-rcp-payment-gateway-stripe.php

Add filter for Stripe subscription args. #800

---

includes/js/admin-scripts.js
includes/process-data.php
includes/scripts.php

Show cancel subscription checkbox when changing status. #557

---

includes/js/register.js

Show payment form when removing an applied discount code #910

---

includes/gateways/class-rcp-payment-gateway-stripe-checkout.php

Hide the spinner when Stripe Checkout closed. #969

---

includes/misc-functions.php

Do not include content with access_level restrictions set to None. #1017

---

includes/class-rcp-member.php

Trim profile IDs before saving. #1031

---

includes/admin/settings/settings.php
uninstall.php

Add option to remove all data on uninstall. #771

---

includes/registration-functions.php

Disable proration if member is renewing current subscription early. #812

---

includes/gateways/class-rcp-payment-gateway-2checkout.php
includes/gateways/class-rcp-payment-gateway-authorizenet.php
includes/gateways/class-rcp-payment-gateway-paypal-express.php
includes/gateways/class-rcp-payment-gateway-paypal-pro.php
includes/gateways/class-rcp-payment-gateway-stripe.php
includes/registration-functions.php

Delete trial meta if registration fails. #999

---

includes/class-rcp-discounts.php
includes/registration-functions.php

Decrease discount code count on registration failure. #560

---

includes/class-rcp-member.php
tests/test-members.php

Update member status check for content restricted to 'any' level. #1041

---

includes/class-rcp-member.php
includes/process-data.php
includes/registration-functions.php

New methods for set_subscription_id and key. #1025

---

includes/gateways/class-rcp-payment-gateway-2checkout.php
includes/gateways/class-rcp-payment-gateway-authorizenet.php
includes/gateways/class-rcp-payment-gateway-paypal-express.php
includes/gateways/class-rcp-payment-gateway-paypal.php
includes/gateways/class-rcp-payment-gateway-stripe.php
includes/gateways/class-rcp-payment-gateway.php
includes/member-functions.php

Add user note when recurring payment fails. #990

---

includes/gateways/braintree/functions.php

Braintree admin notice for PHP version. #1062

---

includes/gateways/braintree/functions.php

Replace usage of wp_doing_ajax(). #1066

---

includes/gateways/class-rcp-payment-gateway-paypal.php

Check payment profile ID before expiring member. #1045

---

templates/register-single.php

Remove subscription level info from single template. #1054

---

includes/captcha-functions.php
includes/js/register.js
includes/scripts.php

Validate reCAPTCHA response before allowing registration form submission. #1037

---

includes/js/register.js

Hide auto renew checkbox for free plans. #1085

---

includes/member-functions.php

Remove upgrade possible check. #1058

---

includes/member-functions.php

Username validation is now case-insensitive. #1047

---

includes/gateways/class-rcp-payment-gateway-stripe.php

Don't set recurring members to active. #1078

---

includes/class-rcp-member.php

Update member status note. #1093

---

includes/admin/members/edit-member.php
includes/css/admin-styles.css
includes/member-functions.php

Remove inline table CSS. #1055

---

templates/subscription.php

Add cancellation confirmation to [subscription_details]. #654

---

includes/class-rcp-member.php
includes/misc-functions.php

Include term restrictions in restricted content check. #1051

---

includes/admin/members/edit-member.php
includes/class-rcp-member.php
includes/member-functions.php

Always use get_expiration_date() method. #1061

---

includes/gateways/class-rcp-payment-gateway-stripe.php

Subtract customer balance on failed transactions. #1097

---

includes/admin/members/members-page.php
includes/gateways/class-rcp-payment-gateway-paypal-express.php

Set user back to pending if initial PayPal Express payment fails. #1060

---

includes/registration-functions.php

Calculate from expiration today if prorating. #1056

---

templates/subscription.php

Close View Receipt anchor tag. #1112

---

includes/gateways/class-rcp-payment-gateway-paypal-express.php

Fix free trials in PayPal Express. #1107

---

templates/register-single.php
templates/register.php

Add login URL to single registration template. #1090

---

tests/test-members.php

Use correct method for setting expiration date in unit tests. #1120

---

includes/admin/members/edit-member.php
includes/admin/members/members-page.php
includes/css/admin-styles.css
includes/js/admin-scripts.js
includes/process-data.php

Add Revoke Access checkbox. #1043

---

includes/class-rcp-member.php
tests/test-members.php

Return early if account isn't active. #1052

---

includes/gateways/class-rcp-payment-gateway.php

Improve gateway documentation. #1100

---

includes/gateways/class-rcp-payment-gateway-stripe.php

Only cancel subscription if IDs match. #1095

---

includes/admin/admin-notices.php
includes/gateways/braintree/functions.php
restrict-content-pro.php

Check capabilities before showing admin notices #1131

---

includes/gateways/class-rcp-payment-gateway-paypal-express.php
includes/gateways/class-rcp-payment-gateway-paypal-pro.php

Fix trials in PayPal Express and PayPal Pro. #1107

---

includes/gateways/class-rcp-payment-gateway-2checkout.php
includes/gateways/class-rcp-payment-gateway-braintree.php
includes/gateways/class-rcp-payment-gateway-stripe-checkout.php
includes/gateways/class-rcp-payment-gateway-stripe.php

Unbind the rcp_register_form_submission handler before binding it. #1154

---

templates/invoice.php

Format prices on invoices. #1152

---

includes/class-rcp-member.php
includes/misc-functions.php

Fix incorrect usage of term_taxonomy_id. #1148

---

includes/registration-functions.php

Round pending subscription amount. #1166

---

includes/class-rcp-emails.php
includes/email-functions.php
includes/invoice-functions.php

Add template tag for latest invoice URL. #1135

---

includes/member-forms.php
includes/shortcodes.php
templates/register-single.php
templates/register.php

Add header attributes to register form shortcode. #677

---

includes/admin/discounts/discount-codes.php
includes/admin/discounts/edit-discount.php
includes/admin/members/edit-member.php
includes/admin/members/members-page.php
includes/admin/payments/edit-payment.php
includes/admin/payments/new-payment.php
includes/admin/subscriptions/edit-subscription.php
includes/admin/subscriptions/subscription-levels.php
includes/css/admin-styles.css

Increase size of price fields and remove inline CSS. #1165

---

includes/admin/payments/edit-payment.php
includes/member-functions.php

Add view invoice link to Edit Payment page. #819

---

includes/gateways/class-rcp-payment-gateway-stripe.php

Add metadata to Stripe subscription. #1175

---

includes/class-rcp-discounts.php

Remove addslashes() when adding/updating discounts. #1181

---

includes/admin/discounts/discount-codes.php
includes/admin/payments/payments-page.php

Reorganize payment table row actions. #1173

---

includes/shortcodes.php

Check if user is in allowed statuses before giving access in [restrict] #1183

---

includes/shortcodes.php

Change label on Stripe Checkout trials. #1191

---

includes/registration-functions.php

Lower priority on rcp_remove_new_subscription_flag() #1199

---

includes/gateways/class-rcp-payment-gateway-stripe.php

Update Stripe customer metadata after payment is made #1186

---

includes/email-functions.php

Don't send renewal email if message or subject is empty. #1201

---

includes/captcha-functions.php
includes/scripts.php
restrict-content-pro.php

Introduce function checking if reCAPTCHA is enabled. #1197

---

includes/integrations/class-rcp-woocommerce.php

Use get_id() for getting WooCommerce product ID. #1202

---

includes/member-forms.php
includes/shortcodes.php
includes/subscription-functions.php
templates/register.php

Add support for multiple levels in register form shortcode #1187

---

restrict-content-pro.php

Change capability required for seeing PHP version notice. #1206

---

includes/registration-functions.php

Fully discounted auto renewing subs shouldn't expire. #1205

---

includes/login-functions.php

Use safe redirect after logging in. #1147

---

includes/integrations/class-rcp-woocommerce.php

Restrict direct access to term restricted products #1213

---

includes/registration-functions.php

Extend expiration date when manually renewing. #1208

---

includes/js/register.js

Add form fields to rcp_calc_total

---

includes/gateways/class-rcp-payment-gateway-stripe.php

Check if transaction ID isn't empty when firing duplicate payment action #1228

---

includes/redirects.php

Pass redirect_to query arg to custom login page URL #1269

---

includes/class-rcp-member.php

strtolower() on selected role restriction #1274

---

includes/gateways/class-rcp-payment-gateway-stripe.php

Save customer after updating source #1277

---

includes/admin/settings/settings.php

Add usage tracking #1304

---

includes/gateways/class-rcp-payment-gateway-paypal.php

Unset empty payment data keys and mark members as recurring. #1332

---

includes/class-rcp-member.php

Remove current status from renewal log. #1330

---

includes/gateways/class-rcp-payment-gateway-2checkout.php
includes/gateways/class-rcp-payment-gateway-authorizenet.php
includes/gateways/class-rcp-payment-gateway-braintree.php
includes/gateways/class-rcp-payment-gateway-paypal-express.php
includes/gateways/class-rcp-payment-gateway-paypal.php
includes/gateways/class-rcp-payment-gateway-stripe.php

Add more logs documenting webhook process #1333

---

templates/register.php

Fix nesting of spans on registration level LI #1338

---

includes/admin/discounts/discount-codes.php

Fix duplicate queries on discounts admin page. #1222

---

templates/card-form.php
templates/card-update-form.php

Increase size of zip code field in card forms. #1258

---

includes/css/admin-styles.css

Set z-index for user search results so they appear on top. #1234

---

includes/class-rcp-emails.php

Fix misspelled email tag description. #1299

---

includes/registration-functions.php

Only give 'free' status if subscription price is 0. #1357

---

includes/deprecated/functions.php
includes/member-functions.php

Deprecate rcp_print_user_payments() #1273

---

includes/gateways/class-rcp-payment-gateway-braintree.php

Send postal code and CVV to Braintree. #1298

---

includes/class-rcp-member.php

Use site local time when setting join date #1361

---

includes/shortcodes.php
templates/subscription.php

Move rcp_load_css variable from template to shortcode function #1289

---

includes/class-rcp-payments.php

Implode user_id argument in earnings cache key. #1223

---

templates/paypal-express-confirm.php

Add table headings for mobile in paypal-express-confirm.php table #1243

---

includes/gateways/class-rcp-payment-gateway-authorizenet.php

Prefix transaction ID with anet_ #1331

---

includes/admin/payments/payments-page.php

Adding "rcp_payments_page_table_row_actions" hook which allows adding more actions to each payment row

Updated payments-page.php

---

includes/gateways/class-rcp-payment-gateway-paypal-express.php

Set member as recurring and don't renew if initial payment #1368

---

includes/email-functions.php
includes/gateways/class-rcp-payment-gateway-stripe.php

Fix template tags by completing Stripe payment right after setting up subscription #1360, #1365

---

includes/class-rcp-member.php

Introduce rcp_set_status_value filter in set_status(). #1328

---

includes/gateways/class-rcp-payment-gateway-paypal.php

Check for pending payment and update status if it exists #1388

---

includes/gateways/class-rcp-payment-gateway-braintree.php

Save payment profile ID if customer already exists. #1308

---

includes/class-rcp-reminders.php

Enable filter for email reminder query args #1395

---

includes/admin/help/help-menus.php
includes/member-functions.php

Allow member search by payment profile ID. #1248

---

includes/gateways/class-rcp-payment-gateway-manual.php
includes/registration-functions.php

Don't set user status to Pending when renewing and fix expiration date calculation. #1397

---

includes/admin/settings/settings.php

Add links to Edit/View RCP pages in settings #1312

---

includes/member-functions.php

Bail early if global post object isn't found. #1324

---

includes/gateways/class-rcp-payment-gateway-stripe.php

Use invoice.payment_failed event for sending failed payment emails in Stripe #1325

---

includes/misc-functions.php

Add filter for restricted content excerpt #1323

---

includes/admin/members/edit-member.php

Show pending subscription and expiration for pending members. #1407

---

templates/login.php

Use shortcode class attribute #1319

---

includes/admin/settings/settings.php

Reword email verification tooltip. #1425

---

includes/shortcodes.php

Allow empty space to be passed into [restrict] message attr #1379

---

includes/class-rcp-emails.php
includes/email-functions.php

Add new %discount_code% email tag #1387

---

includes/gateways/class-rcp-payment-gateway-braintree.php

Don't try to create Braintree token for free subs #1307

---

includes/admin/metabox-view.php

Set default value for 'Members of Subscription Levels' #1346

---

includes/gateways/class-rcp-payment-gateway-paypal-express.php
includes/gateways/class-rcp-payment-gateway-paypal.php

Do not add thousands separator when passing amounts through number_format(). #1433

---

includes/registration-functions.php

Move rcp_form_processing hook below pending payment creation #1438

---

includes/class-rcp-emails.php

Remove payment query from send() method #1441

---

includes/registration-functions.php

Cancel subscription when downgrading to free #1263

---

includes/class-rcp-emails.php

Add $payment_id property in RCP_Emails. #1452

---

includes/class-rcp-payments.php

Only backfill payment data if payment exists #1444

---

includes/misc-functions.php

Use all lowercase in meta key value check #1435

---

includes/subscription-functions.php

Don't show subscription if it is unlimited and the user already has it

---

includes/misc-functions.php

Bail early if logged in cookie is not set #1411

---

includes/admin/admin-pages.php
includes/admin/tools/tools-page.php

Change capability to view Tools page to rcp_manage_settings #1463

---

includes/admin/settings/settings.php
includes/gateways/class-rcp-payment-gateway-stripe-checkout.php
includes/shortcodes.php

Remove Alipay support from Stripe Checkout #1310

---

templates/login.php

Show success message after resetting password #1364

---

includes/admin/admin-notices.php
includes/admin/members/edit-member.php
includes/admin/members/member-actions.php
includes/admin/members/members-page.php

Allow admins to manually verify account emails #1440

---

includes/admin/settings/settings.php
templates/invoice.php

Use visual editor for invoice notes field & wpautop #1467

---

includes/class-rcp-payments.php

Use $wpdb::prepare() & only backfill status if payment is found #1479

---

includes/gateways/class-rcp-payment-gateway-braintree.php

Find member by sub ID if customer ID search has no results #1483

---

includes/gateways/class-rcp-payment-gateway-authorizenet.php

Process single transaction when auto renew is disabled #1239, #1377

---

includes/gateways/class-rcp-payment-gateway-authorizenet.php

Show error if subscription is longer than 1 year #1296

---

templates/register-single.php
templates/register.php

Issues/1489 - Wrap discount fields in <span>

---

includes/gateways/class-rcp-payment-gateway-authorizenet.php

Authorize cards before creating subscriptions #1236

---

templates/register-total-details.php

This reverts commit 0ea2bfb11b6af3fc04ec2c8d4f8810e278f33175.
#1490

Revert "Issues/1490 - Change td to th (#1491)" #1490

---

includes/class-rcp-logging.php

Use timezone offset in RCP_Logging::log(). #1504

---

includes/gateways/class-rcp-payment-gateway-braintree.php

Fix typo in Braintree error message. #1500

---

includes/class-rcp-payments.php

Account for old payments that have status as empty string instead of NULL #1496

---

includes/misc-functions.php

Exclude admin accounts from prevent account sharing #1469

---

templates/subscription.php

Showing pending subscription name if member is pending. #1477

---

includes/admin/payments/payments-page.php

Change class on span wrapping payment delete link. #1501

---

includes/member-forms.php

Add default form class in rcp_login_form_fields(). #1512

---

includes/gateways/class-rcp-payment-gateway-stripe.php

Support \Exception in RCP_Payment_Gateway_Stripe::handle_processing_error(). #1326

---

includes/email-functions.php

Use admin email from settings for manual payment emails #1516

---

includes/registration-functions.php

Run strtolower() on discount code before processing registration #1517

---

includes/member-forms.php

Display registered_message if user isn't eligible for level #1510

---

includes/registration-functions.php

Remove _rcp_new_subscription flag for free users #1522

---

includes/css/admin-styles.css
includes/js/admin-scripts.js

Remove settings tab CSS in favor of core. Fix active tab JS targeting. #1529

---

includes/gateways/class-rcp-payment-gateway-paypal.php

Don't set payment profile ID in PayPal during subscr_payment events. #1526

---

includes/class-rcp-registration.php

Round registration and discount totals #1521

---

templates/register-total-details.php

Add scope attributes and add thead and tfoot tags #1490

---

includes/class-rcp-member.php

Get unformatted expiration date when calculating credits #1532

---

includes/admin/reports/reports-page.php

Explicitly set year_end value for current year. #1537

---

includes/integrations/class-rcp-woocommerce.php

Fix access level check in WooCommerce template visibility check. #1558

---

includes/gateways/class-rcp-payment-gateway-paypal-express.php
includes/gateways/class-rcp-payment-gateway-paypal.php

Use refering page for PayPal cancel URL #1244

---

includes/misc-functions.php

Set 30 day expiry for logged in users transient #1536

---

includes/member-functions.php

Member cannot renew if expiration date is none #1563

---

includes/admin/settings/settings.php
includes/js/admin-scripts.js

Refine JS targeting on settings page. #1573

---

includes/registration-functions.php

Don't change status of free users to pending when upgrading #1551

---

includes/class-rcp-member.php
includes/registration-functions.php

Create pending payment before setting member status. #1442

---

includes/class-rcp-export.php

Improved esc logic in esc_field() to resolve. #1549

---

includes/gateways/class-rcp-payment-gateway-braintree.php

Update Braintree JavaScript to version 2.32.1. #1590

---

includes/class-rcp-reminders.php
includes/cron-functions.php

Add debug logs for cron jobs and reminders. #1588

---

includes/shortcodes.php

Set fallback restriction message. #1542

---

includes/gateways/class-rcp-payment-gateway-braintree.php

Get first/last name and email from member object #1557

---

templates/subscription.php

Add update card link/message to subscription details. #1572

---

includes/registration-functions.php

Log gateway as 'free' for free registrations. #1556

---

includes/gateways/class-rcp-payment-gateway-paypal-pro.php

Limit characters for Soft Descriptor & Soft Descriptor City. #1606

---

includes/class-rcp-reminders.php

Add filter for reminder notice periods #1601

---

uninstall.php

Remove usermeta and custom capabilities on uninstall. #1229

---

includes/admin/members/edit-member.php
includes/admin/members/member-actions.php
includes/class-rcp-member.php
includes/cron-functions.php

Change cancelled users' status to "expired" when they reach expiration date

---

includes/gateways/class-rcp-payment-gateway-stripe.php

Set customer currency when discount code is used. #382

---

includes/shortcodes.php

Only load scripts if user can update card details. #1636

---

includes/email-functions.php

Use pending subscription name in manual payment email. #1638

---

includes/gateways/class-rcp-payment-gateway-paypal-express.php

Use pending subscription key if exists. #1647

---

includes/misc-functions.php

Exit early if provided post type is empty. #1640

---

includes/gateways/class-rcp-payment-gateway-2checkout.php
includes/gateways/class-rcp-payment-gateway-braintree.php
includes/gateways/class-rcp-payment-gateway-paypal-express.php
includes/gateways/class-rcp-payment-gateway-paypal.php
includes/gateways/class-rcp-payment-gateway-stripe.php

Only cancel membership via webhook if member is active. #1646

---

includes/admin/members/member-actions.php

Cancel payment profile before revoking access. #1652

---

includes/query-filters.php

Adjust logic for when restricted posts should be hidden from queries #1651

---

includes/deprecated/functions.php
includes/login-functions.php

Move to standard wp_signon() method of login #1217

---

includes/gateways/class-rcp-payment-gateway-stripe.php

Create Stripe product with plan. #1658

---

templates/invoice.php

Use site date format for payment date in invoice template. #1664

---

includes/class-rcp-levels.php

Fix get_levels() cache clearing on level add/update/delete #646, #790

---

includes/query-filters.php

Exclude admins from query filter. #1680

---

includes/admin/admin-notices.php
includes/admin/reminders/subscription-reminders.php
includes/admin/settings/settings.php
includes/class-rcp-emails.php
includes/template-functions.php

Add 'Preview Email' and 'Send Test Email' buttons for all email templates #1461

---

includes/gateways/class-rcp-payment-gateway-stripe.php

Don't change status to cancelled on new signups #1626

---

includes/admin/settings/settings.php
includes/admin/tools/system-info.php
includes/gateways/class-rcp-payment-gateway-paypal-express.php
includes/gateways/class-rcp-payment-gateway-paypal.php

Remove Email IPN Report feature #1252

---

templates/login.php

Show password reset success message whether logged in or out

---

includes/gateways/class-rcp-payment-gateway-braintree.php

Fix backwards compatibility with old Braintree add-on. #1724

---

includes/registration-functions.php
includes/shortcodes.php

This shows the error messages, and loads our forms css to properly style the error messages.
Closes #1669

Show error messages on Stripe checkout registration

---

includes/deprecated/functions.php
includes/discount-functions.php

Deprecate rcp_check_paypal_return_price_after_discount()

---

templates/paypal-express-confirm.php

Add ID to PayPal Express confirm form. #1737

---

includes/admin/settings/settings.php

Adjust message about PayPal API keys to make required for all PP gataways. #1749

---

includes/admin/admin-actions.php

Identify RCP pages in the list table screen

---

includes/admin/help/help-menus.php
includes/js/admin-scripts.js
includes/misc-functions.php
includes/scripts.php

When a different currency is chosen, this dynamically changes the currency symbol in the Currencty Position select element to match.
Closes #105

Display consistent currency symbol in settings

---

includes/shortcodes.php

Improve Stripe Checkout modal experience in [register_form_stripe] shortcode #1753

---

includes/gateways/class-rcp-payment-gateway-stripe.php

Get Stripe subscription product name instead of plan name. #1746

---

includes/redirects.php

Add filter on redirect URL when redirecting from restricted post #1763

---

includes/gateways/class-rcp-payment-gateway.php

Add trial information to RCP_Payment_Gateway debug log #1760

---

includes/admin/tools/system-info.php

Add level ID and fee to subscription levels in system info. #1773

---

includes/error-tracking.php
includes/js/register.js

Adds ARIA `list` and `listitem` roles to error message wrapper and individual messages, respectively.
Also focuses the error message div if it appears.
Closes #1394
Partially addresses #1621

Improve accessibility of registration form errors

---

includes/admin/discounts/discount-actions.php
includes/admin/members/member-actions.php
includes/admin/payments/payment-actions.php
includes/admin/subscriptions/subscription-actions.php
includes/admin/tools/tools-page.php
includes/class-rcp-emails.php
includes/class-rcp-levels.php
includes/class-rcp-member.php
includes/class-rcp-payments.php
includes/cron-functions.php
includes/gateways/class-rcp-payment-gateway-2checkout.php
includes/gateways/class-rcp-payment-gateway-braintree.php
includes/gateways/class-rcp-payment-gateway-paypal-express.php
includes/gateways/class-rcp-payment-gateway-paypal.php
includes/gateways/class-rcp-payment-gateway-stripe.php
includes/registration-functions.php

Force rcp_log() through when it's a logging a critical error #1766

---

includes/gateways/class-rcp-payment-gateway-paypal.php

Only set member to cancelled when PayPal subscription ID matches current payment profile ID. #1784

---

includes/error-tracking.php

Pass $error_id to rcp_error_messages_html filter #1800

---

templates/register-single.php
templates/register.php

Clarifies that users should log in to renew OR change a subscription.
Closes https://github.com/restrictcontentpro/restrict-content-pro/issues/1688

Improve log in prompt message

---

includes/content-filters.php

Only load CSS if user is pending verification. #1720

---

templates/profile-editor.php

This was originally introduced in https://github.com/restrictcontentpro/restrict-content-pro/commit/2c3d50816e9b0fa9a5ea5a456c6e440f7b4eabf7
However, changing your password does not in fact require logging back in.
Closes #1789

Remove password change log in notice

---

includes/class-rcp-payments.php

Add support for object_id and object_type in RCP_Payments::count() #1620

---

includes/admin/metabox.php
includes/class-rcp-member.php
tests/test-members.php

Don't require a paid account with level restrictions #1569

---

includes/admin/admin-notices.php
includes/admin/subscriptions/subscription-actions.php
includes/class-rcp-levels.php

Show specific error messages on subscription level add/edit failure #1288

---

includes/shortcodes.php

Load scripts on password reset form. #1809

---

includes/admin/settings/settings.php

Fix PHP 5.3 syntax error in Stripe Connect logic. #1812

---

includes/admin/tools/system-info.php

Fix incorrect count() formatting. #1820

---

includes/member-functions.php

Trim value for members search. #1818

---

includes/js/admin-scripts.js

Check for page ID instead of admin page name. #1817

---

includes/admin/members/member-actions.php

Set expiration time to 23:59:59 when bulk editing members. #1816

---

includes/content-filters.php

Only block access to content via REST API if user can't access it

---

includes/registration-functions.php

Delete merchant ID when moving to free/trial level. #1833

---

includes/class-rcp-levels.php

Add support for list_order in adding/updating levels. #1851

---

includes/content-filters.php
includes/deprecated/functions.php
includes/misc-functions.php

Remove filter on excerpt length & set default to 100. #1849

---

includes/registration-functions.php

Get current user ID if not specified #1856

---

includes/class-rcp-payments.php

Add support for date start/end in earnings query #1854
