restrictcontentpro/restrict-content-pro

includes/admin/settings/settings.php

Avoids ambiguity in case multiple pages share a title.
Fixes #130

Show page IDs on settings select lists

---

includes/admin/members/edit-member.php
includes/admin/members/members-page.php
includes/class-rcp-member.php
includes/member-functions.php

If the [user switching](https://wordpress.org/plugins/user-switching/) plugin is active, then user switching links will be displayed on the main members page and on each individual edit member page.
Fixes #129

Add user switching links if possible

---

includes/process-data.php

Comment was referencing a file that no longer exists as of https://github.com/pippinsplugins/Restrict-Content-Pro/commit/55373a7c90b6170f475fe85bf7d716b66d8fd683
Now correctly references includes/registration-functions.php

Correct comment in includes/process-data.php

---

includes/member-functions.php

I cannot think of any good reason that a Stripe member should only be able to update their card details if `$recurring == true`. 
I've had a number of times where a member has expired due to a failed card, where I'd like to be able to reactivate them on their behalf after they update their card details. This is not currently possible though because `$recurring` gets set to false upon expiration. 
Thoughts @pippinsplugins?

Remove requirement for  in order for Stripe customers to update their card

---

includes/member-functions.php

In PHP empty() does not support checking a constant. It only allows variables and expressions. This will cause PHP to throw an error expecting :: as it is looking for an object with the name TWOCHECKOUT_ADMIN_USER and TWOCHECKOUT_ADMIN_PASSWORD. Because the defined() check is above this empty() check may be redundant. If the user does put an empty string in then using the constant would fail, just as it would if they input an invalid password.

Remove condition with empty( CONSTANT ) check

---

includes/cron-functions.php

Hello Pippin,
we just added some hooks to make sure we can avoid members using our Payflow gateway from expiring right away. Our code tries to check for a payment again in a week and only then expires the user. 
Thanks,
Martin

Add filters to cron queries

---

includes/class-rcp-discounts.php
includes/process-data.php
tests/test-discounts.php

#328.
I need some feedback. I'm not sure about this approach, and I'm not aware of what other things might hook into this.
Stripe doesn't allow percentage discounts with a decimal. For example, you can't use 25.5%.
With that in mind, the PR prevents decimals in percentage discounts. If we need to allow them for other reasons, we'll need to do some gateway detection and/or create a map of allowed discount formats for each gateway.
Things this PR addresses:
- if someone fails to enter a discount amount, it throws a notice and does not create the discount.
- checks that percentage discounts are whole numbers between 1 and 100, based on the comment above, and throws a notice if it doesn't fall within the range 
- ensures the amount entered is a valid number
Since this needs to run in at least …

Validate input during discount code creation and updates. #328.

---

.travis.yml

- Added WordPress 4.4 single and multisite builds
- Added WordPress 4.3 multisite build
- Added WordPress 4.2, 4.1, and 4.0 single install builds
- Added matrix to include WordPress trunk on PHP 7, exclude WordPress 4.0 from HHVM, and allow failures for PHP 7 and nightly

Add PHP nightly and composer self-update to Travis

---

includes/class-rcp-discounts.php
tests/test-discounts.php

Do not format the amount returned by calc_discounted_price(). #602

Return non-formatted amount in calc_discounted_price(). #602

---

templates/invoice.php

The logo on my site was spilling out of the `div`. This makes sure it never gets bigger than the `div` it is contained in.

Make sure logo doesn't get too big on invoice

---

includes/admin/members/edit-member.php

#710 was not working because the textual date is in a foreign language (French for me, Spanish for @boluda) so not accepted by the [date function format](http://php.net/manual/en/datetime.formats.date.php). And, as the inverse function of [date_i18n](https://codex.wordpress.org/Function_Reference/date_i18n) does not seem to exist, this change puts directly the format expected by the from processor in the input. So when I validate without editing this field, it is not reinitialized to 1 Jan. 1970. Moreover, the datepicker works fine: already setting the content of the input field to `Y-m-d` format.
*Before that, I had to set it to the right format (i.e. 2016-10-16) manually or selecting the date with the datepicker before submitting the form, otherwise the date was set to 1 Jan. 1970. See …

Set expected format in the input of user's expiration date. #704

---

includes/member-forms.php

When the user clicks on the link of the login form to reset his password then clicks on the link in the email he received to set a new password, he reaches the reinit password form. 
If everything is fine when he enters his new password, he is redirected properly to the login form and can log in. However, if he put nothing in the reinit password form or if the two password fields do not match, the same occurs : he is redirected to the login form (without error message !) whereas the password was not changed. So I receive complaints from people who think they have changed their password (whereas they mistook in the form) but cannot login because the password was not actually reset...
This fix from @thomasfw in #354 changes the behavior if the user mistakes : the reinit password form is …

Fix not showing again reinit password form when error in this form. #354

---

restrict-content-pro.php

If someone's PHP version is lower than 5.3, none of the plugin files get loaded, but the `rcp_register_databases` action still triggers. This causes a fatal error when trying to use classes (like `RCP_Payments`) that don't exist.
Moving the action into the `else` block for the version check fixes the problem.

Fix fatal error on unsupported PHP versions

---

includes/login-functions.php
includes/member-functions.php

Pantheon requires cookies that need to get back to the server to be prefixed. If you add a filter here, it would allow developers the ability to change the cookie name to allow the cookie to bypass caching filters. Docs: https://pantheon.io/docs/cookies/

Cookie name filter

---

includes/gateways/stripe/functions.php

The Stripe gateway code attempts to create discount codes in Stripe when
one is created in RCP. However, it does not use the information made
available to the hook, instead grabbing data out of $_POST. This fails
when the discount code is being created programatically.
This change passes in the discount args, and uses them instead of $_POST.

Fix programmatic discount code creation errors in Stripe gateway.

---

includes/gateways/class-rcp-payment-gateway-stripe.php

Closes #977
`$payment_event` was [previously called](https://github.com/restrictcontentpro/restrict-content-pro/commit/914236488e689da58faff904a4797d8778f1254c#diff-db6e56469eb0cb6ce966bd803fc70da4R438) `$invoice`; when it got switched to `$payment_event` this line was missed.

Fix undefined variable bug

---

includes/gateways/class-rcp-payment-gateway-stripe.php

I don't _think_ there's any downside to this, it should be fully backwards compatible, and it allows for using the stripe event data to inform what actions an extension might want to take. Probably a bit of an edge case in terms of usefulness, but it'd be handy for something I'm working on right now.

Pass $event to rcp_stripe_charge_succeeded hook

---

includes/gateways/paypal/functions.php

Don't assign wp_parse_str value to variable. #1293

---

includes/class-rcp-emails.php

As documented in wp_mail() the $to parameter accepts also an array, updated RCP_Emails::send() function documentation.
```
[...]
@global PHPMailer $phpmailer
@param string|array $to          Array or comma-separated list of email addresses to send message.
@param string       $subject     Email subject
[...]
```

Updated doc for RCP_Emails\send(): $to param accepts arrays

---

includes/member-functions.php

Adds a new filter, `rcp_verification_redirect_url`, allowing users to redirect to an arbitary URL after clicking an email verification link.
Fixes #1414.

Make post-verification redirect filterable

---

includes/admin/payments/edit-payment.php
includes/admin/payments/new-payment.php

Added following actions:
`rcp_add_payment_before`
`rcp_add_payment_after`
`rcp_edit_payment_before`
`rcp_edit_payment_after`
Allow third-party plugins to print custom meta fields in new payment and edit payment pages.
Related to #1449.

Actions for custom fields in signle payment admin page. #1449

---

includes/install.php

Closes https://github.com/restrictcontentpro/restrict-content-pro/issues/1486
I tried to follow what appear to be existing naming patterns for hooks in RCP; obviously it's fine if a different name is used.

Add rcp_create_tables hook

---

RCP_Plugin_Updater.php
includes/admin/add-ons.php
includes/admin/class-rcp-add-on-updater.php
includes/admin/settings/settings.php
includes/gateways/class-rcp-payment-gateway-paypal-express.php

Removes all instances of sslverify being set to false. Because sslverify
defaults to true, we don't need to explicitly set it to true.
This commit also reformats the affected arrays to span multiple lines where
appropriate, for easier human parsing of future changes (e.g. only the affected
line gets changed if an element is added/removed, vs. the entire array
showing in the diff).
Closes #1550

Do not set sslverify to false

---

includes/class-rcp-emails.php

Replace &#038; with &amp; in HTML emails to fix SendGrid tracking. #1585

---

includes/admin/settings/settings.php
includes/member-functions.php

Also improves wording on settings page.
Closes #1729

Only disable WP toolbar for members (subscriber role)

---

includes/integrations/class-rcp-google-authenticator.php

Adjust Google Auth footer hook to fix strict standards warning. #1797

---

composer.json

This updates `composer.json` to require `^1.0.6` instead of `~1.0.6`.
Technically speaking, this just means Composer will allow resolving the `composer/installers` package to any version greater than or equal to `1.0.6` and less than `2.0.0`.
The tilde would only allow greater than or equal to `1.0.6` and less than `1.1.0`.
This makes RCP possible to install in any environments that use more recent versions of `composer/installers` (it's on `1.5.0` at the moment).
Fixes #1834.

Replace tilde with caret in Composer installers requirement

---

includes/admin/tools/system-info.php

Fixes #1862 by adding a timestamp at the bottom of the system info file with the date/time the file is generated.
(Note that this info is also available in the date/time format setting under the "WordPress Configuration" section as well, but I think it's nice to have at the bottom too!)

Add timestamp to the system info
